services:
  mongo: 
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=admin
    networks:
      - mongo-network
    volumes:
      - mongo-data:/data/db

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo-data: